### ISSUE TITLE
Implement orientation handling on Android

### ISSUE THREAD

**Issue by rekola** [Sometrik/framework#1]
If the device orientation changes, display dimensions must be reversed. For example, if the screen size is 1024 x 768 in landscape mode, and the device is rotated to portrait mode, the display dimensions should now be 768 x 1024, and FWContextBase::onResize() method must be called for the new size. Touch coordinates, for example, must be similarly altered.

On iOS all this happens automatically, but you should investigate how this should be handled on Android.

**Comment by MSuni** [comment]
Fixed on commit https://github.com/Sometrik/framework/commit/30a18da351cd500241853da17b0e906cdc97f8ca
