### ISSUE TITLE
Configure AndroidPlatform properly on initialization

### ISSUE THREAD

**Issue by rekola** [Sometrik/framework#14]
In the method Java_com_sometrik_framework_MyGLRenderer_onInit, you must set the variables displayScale and hasES3.

**Comment by MSuni** [comment]
Fixed in 2910fb4af2afd219c33d716a6034a33f8e2bea09 and 01fd038f4665c239576bec62bffe59f5325c6a58

**Comment by rekola** [comment]
Really? You did not actually configure the ES3 support. We need to know if OpenGL ES3 is supported, so we can use all the new features.

You probably have to create an ES3 context for OpenGL and if it success, you then know you have ES3. If it doesn't succeed, you try creating ES2 context:

https://developer.android.com/guide/topics/graphics/opengl.html#version-check

**Comment by rekola** [comment]
No. ConfigurationInfo is the configuration of the Application - i.e. what OpenGL version the application requires.

**Comment by MSuni** [comment]
Version is currently given correctly
