### ISSUE TITLE
No UTF-8 support in Command creation and modalEnd()

### ISSUE THREAD

**Issue by rekola** [Sometrik/framework#15]
Use either modified UTF-8 or UTF-16. Text must be converted, of course.

**Comment by MSuni** [comment]
Turns out NewStringUTF and GetStringUTFChars both return modified UTF-8.

**Comment by rekola** [comment]
no

**Comment by rekola** [comment]
Fixed for Command events. Please test.

**Comment by rekola** [comment]
Works. Fixed.
