### ISSUE TITLE
SET_INT_VALUE and SET_TEXT_VALUE are not handled by any input views

### ISSUE THREAD

**Issue by rekola** [Sometrik/framework#168]
Views that should handle them:
- TextLabel
- TextField
- Picker
- Checkbox
- Switch
- Button
- Image

If a value is sent to Button it should emit a flash or some animation.

**Comment by MSuni** [comment]
These functions are now handled mostly. I also added some demo animation on button text change on 434e1dea463ebc3b481aba2c1e13e61192e15867
