### ISSUE TITLE
App doesn't compile without OpenGL support

### ISSUE THREAD

**Issue by MSuni** [Sometrik/framework#188]
Button needs OpenGL so it doesn't really compile without:

In Button.h, line 65:
- undefined reference to `canvas::OpenGLTexture::createTexture(canvas::Surface&)`

In OpenGLTexture.h:
- undefined reference to `canvas::OpenGLTexture::freed_textures`
- undefined reference to `canvas::OpenGLTexture::total_textures`

In UIElement.h:
- undefined reference to `VBO::quad2d(float, float, float, float, float, float, float, float)`
- undefined reference to `vtable for canvas::OpenGLTexture`

In VBO.h:
- undefined reference to `vtable for VBO`

**Comment by MSuni** [comment]
Also this on APP_PLATFORM := android-17

fatal error: GLES3/gl3.h: No such file or directory

**Comment by rekola** [comment]
Fixed.
