### ISSUE TITLE
Implement CREATE_TEXTVIEW for Android

### ISSUE THREAD

**Issue by rekola** [Sometrik/framework#193]
CREATE_TEXTVIEW creates a scrollable editable multiline text field. Since the text content can be huge, it shouldn't be sent to the App everytime it changes. Instead a small edit command should be sent, such as insert-text or remove-text.

**Comment by MSuni** [comment]
CREATE_TEXTVIEW implemented. Still todo is creating a fitting listener and commands

**Comment by rekola** [comment]
This is unnecessary, for now.
