### ISSUE TITLE
Implement command REORDER_CHILD

### ISSUE THREAD

**Issue by rekola** [Sometrik/framework#443]
This commands sets the position of a view among the other subviews of a UIStackView. The new position of the child is given in command.getValue(). For example, if the new position of a child is 0, it will be moved to the top of the UIStackView.

**Comment by sakrra** [comment]
implemented.

**Comment by rekola** [comment]
Didn't work. The code made a mutable copy out of the subviews array, and then modified the copy, which obviously did not alter the original. I made another attempt, which does not work either, but the problem may lie elsewhere.

**Comment by rekola** [comment]
The second attempt did work.
