### ISSUE TITLE
Add nice toolbar to the web browser

### ISSUE THREAD

**Issue by rekola** [Sometrik/framework#602]
Currently, the in-app web browser has a close button for closing the browser, but it gets easily mixed up with the web content. Replace the close button with a toolbar similar to what Facebook has.

The toolbar doesn't need to have any functionality other than back button for closing the browser, but if there is some functionality that is easy and quick to add, feel free to implement such. Perhaps the toolbar could have a view that shows the current url or page title. Also, a button that opens an action sheet with application specified actions would be nice.

**Comment by sakrra** [comment]
Done
