### ISSUE TITLE
statusBarBackgroundView functionality is not ideal

### ISSUE THREAD

**Issue by rekola** [Sometrik/framework#612]
* If personal hotspot is active when the app is started, the statusBarBackgroundView goes below the blue personal hotspot banner, and takes unnecessary space

* Blurring is not smooth. There is a discontinuity in the blurred background of the statusBarBackgroundView and the navBar.

**Comment by sakrra** [comment]
Done. Using fixed height for status bar (it doesn't break layout). Blurring seems fine, didn't touch anything there.
