### ISSUE TITLE
statusBarBackgroundView has invalid bounds when switching orientations

### ISSUE THREAD

**Issue by rekola** [Sometrik/framework#644]
When the application is launched in portrait mode and then device is rotated to landscape mode, the statusBarBackgroundView is visible and takes space, even though it is not needed.

When the application is launched in landscape mode, the background view has zero height as it should have, but when the device is rotated to portrait mode, the background view still has zero height.

This problem is not very important, but it highlights the issues with the status bar background. Perhaps the current approach is not correct?

Have you considered this approach: https://stackoverflow.com/a/20967695

**Comment by sakrra** [comment]
Done by updating constraint and using above solution. Now status bar is not visible when in landscape view and visible when in portrait...
