### ISSUE TITLE
Android doesn't handle DELETE_ELEMENT command

### ISSUE THREAD

**Issue by rekola** [Sometrik/framework#81]

**Comment by rekola** [comment]
Command added, but needs to be handled on Android.

**Comment by MSuni** [comment]
RemoveChild was added to NativeCommandHandler. Call was added here be85c163c8e8ca81f46b13ad913069c37219e4ce and it can be seen implemented here e3c3f622c7dd62e82ab5fb198f6f5d76d05aa772
